# config file
spring:
  application:
    name: geminibi-backend
  profiles:
    active: dev
  #  swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/geminibi_db
server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000

knife4j:
  enable: true
  openapi:
    title: "Swagger UI"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.rayzhou.springboottemplate.controller
  setting:
    language: en